module.exports = {
	content: ["./index.html", "./src/**/*.{gleam,mjs}"],
	daisyui: {
		themes: [
			{
				light: {
					"color-scheme": "light",
					"primary": "oklch(49.12% 0.3096 275.75)",
					"secondary": "oklch(69.71% 0.329 342.55)",
					"secondary-content": "oklch(98.71% 0.0106 342.55)",
					"accent": "oklch(76.76% 0.184 183.61)",
					"neutral": "#2B3440",
					"neutral-content": "#D7DDE4",
					"base-100": "oklch(100% 0 0)",
					"base-200": "#F2F2F2",
					"base-300": "#E5E6E6",
					"base-content": "#1f2937",

					"--rounded-box": "1rem",
					"--rounded-btn": "0.5rem",
					"--rounded-badge": "1.9rem",
					"--animation-btn": "0.25s",
					"--animation-input": "0.2s",
					"--btn-focus-scale": "0.95",
					"--border-btn": "1px",
					"--tab-border": "1px",
					"--tab-radius": "0.5rem",
				},
				dark: {
					"color-scheme": "dark",
					"primary": "oklch(65.69% 0.196 275.75)",
					"secondary": "oklch(74.8% 0.26 342.55)",
					"accent": "oklch(74.51% 0.167 183.61)",
					"neutral": "#2a323c",
					"neutral-content": "#A6ADBB",
					"base-100": "#1d232a",
					"base-200": "#191e24",
					"base-300": "#15191e",
					"base-content": "#A6ADBB",

					"--rounded-box": "1rem",
					"--rounded-btn": "0.5rem",
					"--rounded-badge": "1.9rem",
					"--animation-btn": "0.25s",
					"--animation-input": "0.2s",
					"--btn-focus-scale": "0.95",
					"--border-btn": "1px",
					"--tab-border": "1px",
					"--tab-radius": "0.5rem",
				},
			},
		],
		darkTheme: "dark",
		base: true,
		styled: true,
		utils: true,
		prefix: "",
		logs: true,
		themeRoot: ":root",
	},
	theme: {
		extend: {
			fontFamily: {
				sans: [
					'"Source Sans 3"',
					"ui-sans-serif",
					"system-ui",
					"sans-serif",
					'"Apple Color Emoji"',
					'"Segoe UI Emoji"',
					'"Segoe UI Symbol"',
					'"Noto Color Emoji"',
				],
				serif: [
					'"Source Serif 4"',
					"ui-serif",
					"Georgia",
					"Cambria",
					'"Times New Roman"',
					"Times",
					"serif",
				],
				mono: [
					'"Source Code Pro"',
					"ui-monospace",
					"SFMono-Regular",
					"Menlo",
					"Monaco",
					"Consolas",
					'"Liberation Mono"',
					'"Courier New"',
					"monospace",
				],
			},
		},
	},
	plugins: [
		require("@tailwindcss/typography"),
		require("@tailwindcss/aspect-ratio"),
		require("../node_modules/daisyui"),
		require("../node_modules/tailwindcss-motion"),
	],
};
