name = "immutype_lite"
version = "1.0.0"
gleam = ">= 1.6.2"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
sqlight = ">= 0.9.1 and < 1.0.0"
clip = ">= 0.6.1 and < 1.0.0"
chomp = ">= 0.4.0 and < 1.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
birl = ">= 1.7.1 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
