name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up Erlang"
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.0"
          gleam-version: "1.6.0"
          rebar3-version: "3"
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 22.x
            cache: "npm"


      # Download dependencies
      - name: "Download widgets dependencies"
        run: cd widgets && gleam deps download
        
      - name: "Download editor dependencies"
        run: cd editor && gleam deps download

      - name: "Download immutype lite dependencies"
        run: cd immutype_lite && gleam deps download

      - name: "Download backend dependencies"
        run: cd backend && gleam deps download

      - name: "Install other dependencies"
        run: ./scripts/install.sh


      # Run tests
      - name: "Run widgets tests"
        run: cd widgets && gleam test
        
      - name: "Run editor tests"
        run: cd editor && gleam test
        
      - name: "Run immutype lite tests"
        run: cd immutype_lite && gleam test

      - name: "Run backend tests"
        run: cd backend && gleam test


      # Check formatting
      - name: "Check widgets formatting"
        run: cd widgets && gleam format --check src test
        
      - name: "Check editor formatting"
        run: cd editor && gleam format --check src test
        
      - name: "Check immutype lite formatting"
        run: cd immutype_lite && gleam format --check src test

      - name: "Check backend formatting"
        run: cd backend && gleam format --check src test

      
      # Build
      - name: "Build project"
        run: ./scripts/build.sh

      
      # Clean up Gleam
      - name: "Clean up widgets"
        run: cd widgets && gleam clean
      
      - name: "Clean up editor"
        run: cd editor && gleam clean
      
      - name: "Clean up immutype lite"
        run: cd immutype_lite && gleam clean

      - name: "Clean up backend"
        run: cd backend && gleam clean
        